#!/usr/bin/perl -w

use warnings;
use strict;
use v5.10;

my $aux;
my $line;

die "I need a file!" if @ARGV == 0;

open(INPUT, "<", $aux = shift @ARGV) 
or die "Impossible to open \"$aux\"";

open(OUT, '>', $aux . ".lst");
select OUT;

while($line = <INPUT>)
{
    while($line =~ s/(\w\w+)//)
    {
        say $1;
    }
}
